### ISSUE TITLE
Bot detects same posts of r/all

### ISSUE THREAD

**Issue by MysticalUser** [Toldry/RedditAutoCrosspostBot#24]
If “r/all” is commented, the bot will detect the comment’s post in r/all, giving false positives for original content.

**Comment by Toldry** [comment]
Thanks for the report.

Here's a link to the referred comment by the bot, for future reference:

https://www.reddit.com/r/antimeme/comments/p089ph/this_invention_could_come_in_handy_if_theres_a/h87th2u/

I'll work on a fix
