### ISSUE TITLE
On a Family Rated Video Game Board, Bot Links to Porn

### ISSUE THREAD

**Issue by nickwelp** [Toldry/RedditAutoCrosspostBot#34]
https://www.reddit.com/r/ExiledKingdoms/comments/qkga2x/guys/

```
level 2
sub_doesnt_exist_bot
·
11h

The subreddit r/thingsthatmakeyougohmmm does not exist.

Did you mean?:

    r/PornThatMakesYouGoMmm

Consider creating a new subreddit r/thingsthatmakeyougohmmm.

```

**Comment by Toldry** [comment]
Thank you for reporting this. 

I need to think what can be a proper fix for this... my first though is to check whether the suggested subreddit is NSFW and to disclude it if the current subreddit isn't NSFW.

**Comment by Toldry** [comment]
I've decided instead to just mark all `over18` subreddits as **NSFW**. I hope this solution will be sufficient.

If not, this issue may be reopened.
