### ISSUE TITLE
Don't listen for subs less than 3 characters

### ISSUE THREAD

**Issue by gastrodon** [Toldry/RedditAutoCrosspostBot#4]
Reddit users cannot create a sub with fewer than 3 characters in the name 

[Relevant comment](https://www.reddit.com/r/FortNiteBR/comments/ko1a8e/-/ghparx8)

**Comment by Toldry** [comment]
I'm not sure that's accurate, though

https://www.reddit.com/r/de

is a subreddit with a 2-character name

**Comment by gastrodon** [comment]
> Reddit users cannot create a sub with fewer than 3 characters in the name

`r/de` was created by Reddit.
This can be demonstrated by trying to create an unoccupied subreddit with fewer than 3 characters

In fact, if you tried to create a sub suggested by your own bot, it would not work.
![ew](https://user-images.githubusercontent.com/10934565/103450365-4d863580-4c83-11eb-8ab0-0481cf8dbd15.png)

**Comment by Toldry** [comment]
![image](https://user-images.githubusercontent.com/7353619/103452762-73d7bf80-4cdb-11eb-90e3-64a408127214.png)
